---
networks:
  penpot:

volumes:
  penpot_postgres_v15:
  penpot_assets:

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    restart: always
    ports:
      - 9001:80
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      - penpot-backend
      - penpot-exporter
    networks:
      - penpot
    env_file: ../stack.env
    environment:
      - PENPOT_FLAGS=enable-login-with-oidc disable-login-with-password disable-registration

  penpot-backend:
    image: "penpotapp/backend:latest"
    restart: always
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      - penpot-redis
    networks:
      - penpot
    env_file: ../stack.env
    environment:
      - PENPOT_FLAGS=disable-email-verification enable-smtp enable-prepl-server enable-login-with-oidc disable-login-with-password disable-registration

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    restart: always
    networks:
      - penpot

    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=http://penpot-frontend

      ## Redis is used for the websockets notifications.
      - PENPOT_REDIS_URI=$PENPOT_REDIS_URI

  penpot-redis:
    image: redis:7
    restart: always
    networks:
      - penpot