---
volumes:
  qbittorrent:
    driver_opts:
      type: cifs
      o: "username=$QBITTORRENT_SMB_USR,password=$QBITTORRENT_SMB_PWD,addr=$SMB_HOST,rw,uid=3001,gid=3001"
      device: "//$SMB_HOST/qbittorrent"
  qbittorrent-config:
    driver_opts:
      type: cifs
      o: "username=$QBITTORRENT_SMB_USR,password=$QBITTORRENT_SMB_PWD,addr=$SMB_HOST,rw,uid=3001,gid=3001"
      device: "//$SMB_HOST/qbittorrent-config"
  jellyfin:
    driver_opts:
      type: cifs
      o: "username=$JELLYFIN_SMB_USR,password=$JELLYFIN_SMB_PWD,addr=$SMB_HOST,rw,uid=3001,gid=3001"
      device: "//$SMB_HOST/jellyfin"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      PUID: 3001
      PGID: 3001
      TZ: Etc/UTC
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - qbittorrent-config:/config
      - qbittorrent:/downloads
      - jellyfin:/jellyfin
    env_file: ../stack.env

