version: '3'
volumes:
  joplin-data:
    driver_opts:
      type: cifs
      o: "username=$JOPLIN_SMB_USR,password=$JOPLIN_SMB_PWD,addr=$JOPLIN_SMB_HOST,rw,uid=1000,gid=1000"
      device: "//$JOPLIN_SMB_HOST/directus-uploads"
 
services:
    app:
        image: joplin/server:latest
        ports:
            - "22300:22300"
        restart: unless-stopped
        volumes:
            - joplin-data:/data
        env-file: ../stack.env
