version: "3.2"
services:

  outline:
    image: outlinewiki/outline:0.72.0
    env_file: ../stack.env
    ports:
      - "3000:3000"
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - redis

  redis:
    image: redis
    env_file: ../stack.env
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

volumes:
  storage-data:
    driver_opts:
      o: "username=outline,password=$OUTLINE_CIFS_PWD,addr=192.168.50.106,uid=1000,gid=1000,forceuid,forcegid"
      type: cifs
      device: "//192.168.50.106/outline"
