---
volumes:
  ytdl_video:
    driver_opts:
      type: cifs
      o: "username=$JENNY_SMB_USR,password=$JENNY_SMB_PWD,addr=$JENNY_SMB_HOST,rw,uid=1015,gid=1019"
      device: "//$JENNY_SMB_HOST/jenny/ytdl_video"
  ytdl_audio:
    driver_opts:
      type: cifs
      o: "username=$JENNY_SMB_USR,password=$JENNY_SMB_PWD,addr=$JENNY_SMB_HOST,rw,uid=1015,gid=1019"
      device: "//$JENNY_SMB_HOST/jenny/ytdl_audio"

services:
  metube:
    image: alexta69/metube
    container_name: metube-jenny
    restart: unless-stopped
    environment:
      DOWNLOAD_DIR: /downloads_video
      AUDIO_DOWNLOAD_DIR: /downloads_audio 
      UID: 1006
      GID: 1008
    ports:
      - "8988:8081"
    volumes:
      - ytdl_video:/downloads_video
      - ytdl_audio:/downloads_audio
    env_file: ../stack.env

