services:
  sillytavern:
    container_name: sillytavern
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '8000:8000'
    restart: unless-stopped
    image: 'ghcr.io/sillytavern/sillytavern:latest'


volumes:
  sillytavern:
    driver_opts:
      type: cifs
      o: "username=$SILLYTAVERN_SMB_USR,password=$SILLYTAVERN_SMB_PWD,addr=$SILLYTAVERN_SMB_HOST,rw,uid=1006,gid=1008"
      device: "//$SILLYTAVERN_SMB_HOST/ytdl_video"

