services:
  sillytavern:
    container_name: sillytavern
    environment:
      - TZ=Asia/Shanghai
      - SILLYTAVERN_WHITELISTMODE=$SILLYTAVERN_WHITELISTMODE
      - SILLYTAVERN_LISTEN=$SILLYTAVERN_LISTEN
	  - SILLYTAVERN_WHITELISTMODE=$SILLYTAVERN_WHITELISTMODE
	  - SILLYTAVERN_BASICAUTHMODE=$SILLYTAVERN_BASICAUTHMODE
	  - SILLYTAVERN_BASICAUTHUSER_USERNAME=$SILLYTAVERN_BASICAUTHUSER_USERNAME
	  - SILLYTAVERN_BASICAUTHUSER_PASSWORD=$SILLYTAVERN_BASICAUTHUSER_PASSWORD
      - SILLYTAVERN_PORT=$SILLYTAVERN_PORT
      - SILLYTAVERN_WHITELIST='["::1", "127.0.0.1", "192.168.0.0/16", "100.72.197.128"]'
      - SILLYTAVERN_DATAROOT=/sillytavern_data
    ports:
      - '8002:8002'
    restart: unless-stopped
    image: 'ghcr.io/sillytavern/sillytavern:latest'
    volumes:
      - sillytavern:/sillytavern_data


volumes:
  sillytavern:
    driver_opts:
      type: cifs
      o: "username=$SILLYTAVERN_SMB_USR,password=$SILLYTAVERN_SMB_PWD,addr=$SILLYTAVERN_SMB_HOST,rw,uid=1006,gid=1008"
      device: "//$SILLYTAVERN_SMB_HOST/sillytavern"

