services:
  sillytavern:
    container_name: sillytavern
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '8000:8000'
    restart: unless-stopped
    image: 'ghcr.io/sillytavern/sillytavern:latest'
